# Exercise 2.A Fundamentals of pandas

In [1]:
import numpy as np
import pandas as pd

## Series

In [2]:
aa = [1, 2, 3, 4]

ab = (5, 6, 7, 8)

ac = {9, 10, 11, 12}

ad = {
    "first": 13,
    "second": 14,
    "third": 15,
    "fourth": 16
}

In [3]:
ser1 = pd.Series(aa)

ser2 = pd.Series(ab)

# A set is unordered, so I converted it to a sorted list first.
ser3 = pd.Series(sorted(ac))

ser4 = pd.Series(ad)

print("ser1:")
print(ser1)

print("\nser2:")
print(ser2)

print("\nser3:")
print(ser3)

print("\nser4:")
print(ser4)

ser1:
0    1
1    2
2    3
3    4
dtype: int64

ser2:
0    5
1    6
2    7
3    8
dtype: int64

ser3:
0     9
1    10
2    11
3    12
dtype: int64

ser4:
first     13
second    14
third     15
fourth    16
dtype: int64

In [4]:
try:
    ser5 = pd.Series(17, 18, 19, 20)

except TypeError as error:
    print(error)

# TypeError message:
# Index(...) must be called with a collection of some kind, 18 was passed

Index(...) must be called with a collection of some kind, 18 was passed

## DataFrames from Series

In [5]:
df1 = pd.DataFrame(ser1, columns=["ser1"])

df1

   ser1
0     1
1     2
2     3
3     4

In [6]:
df1.insert(1, "ser2", ser2)

df1.insert(2, "ser3", ser3)

df1

   ser1  ser2  ser3
0     1     5     9
1     2     6    10
2     3     7    11
3     4     8    12

In [7]:
df1["ser4"] = ser4

df1

# ser4 is different because it was created from a dictionary.
# The dictionary created labels like "first", "second", "third", and "fourth".
# df1 uses number indexes like 0, 1, 2, and 3.
# Since the indexes do not match, pandas fills the ser4 column with NaN.

   ser1  ser2  ser3  ser4
0     1     5     9   NaN
1     2     6    10   NaN
2     3     7    11   NaN
3     4     8    12   NaN

In [8]:
df1.loc[4] = [5, 9, 12, 0]

df1

   ser1  ser2  ser3  ser4
0     1     5     9   NaN
1     2     6    10   NaN
2     3     7    11   NaN
3     4     8    12   NaN
4     5     9    12   0.0

## Reading Data into a DataFrame

In [10]:
df2 = pd.read_csv("sakila_example.csv")

df2

,last_name,first_name,title,description,genre,no_of_times_rented
0,AKROYD,CHRISTIAN,HILLS NEIGHBORS,A Epic Display of a Hunter And a Feminist who ...,Action,25
1,AKROYD,CHRISTIAN,MAGNOLIA FORRESTER,A Thoughtful Documentary of a Composer And a E...,Action,11
2,AKROYD,CHRISTIAN,DOORS PRESIDENT,A Awe-Inspiring Display of a Squirrel And a Wo...,Animation,19
3,AKROYD,CHRISTIAN,LUKE MUMMY,A Taut Character Study of a Boy And a Robot wh...,Animation,7
4,AKROYD,CHRISTIAN,BACKLASH UNDEFEATED,A Stunning Character Study of a Mad Scientist ...,Children,19
...,...,...,...,...,...,...
5241,ZELLWEGER,MINNIE,HYSTERICAL GRAIL,A Amazing Saga of a Madman And a Dentist who m...,Sports,15
5242,ZELLWEGER,MINNIE,PICKUP DRIVING,A Touching Documentary of a Husband And a Boat...,Sports,16
5243,ZELLWEGER,MINNIE,GROOVE FICTION,A Unbelieveable Reflection of a Moose And a A ...,Sports,18
5244,ZELLWEGER,MINNIE,TALENTED HOMICIDE,A Lacklusture Panorama of a Dentist And a Fore...,Sports,29
5245,ZELLWEGER,MINNIE,MADIGAN DORADO,A Astounding Character Study of a A Shark And ...,Travel,10

In [11]:
df2.head()

,last_name,first_name,title,description,genre,no_of_times_rented
0,AKROYD,CHRISTIAN,HILLS NEIGHBORS,A Epic Display of a Hunter And a Feminist who ...,Action,25
1,AKROYD,CHRISTIAN,MAGNOLIA FORRESTER,A Thoughtful Documentary of a Composer And a E...,Action,11
2,AKROYD,CHRISTIAN,DOORS PRESIDENT,A Awe-Inspiring Display of a Squirrel And a Wo...,Animation,19
3,AKROYD,CHRISTIAN,LUKE MUMMY,A Taut Character Study of a Boy And a Robot wh...,Animation,7
4,AKROYD,CHRISTIAN,BACKLASH UNDEFEATED,A Stunning Character Study of a Mad Scientist ...,Children,19

In [12]:
df2.tail(10)

,last_name,first_name,title,description,genre,no_of_times_rented
5236,ZELLWEGER,MINNIE,JAPANESE RUN,A Awe-Inspiring Epistle of a Feminist And a Gi...,Horror,6
5237,ZELLWEGER,MINNIE,MANNEQUIN WORST,A Astounding Saga of a Mad Cow And a Pastry Ch...,New,5
5238,ZELLWEGER,MINNIE,DAY UNFAITHFUL,A Stunning Documentary of a Composer And a Mad...,New,14
5239,ZELLWEGER,MINNIE,EXPRESS LONELY,A Boring Drama of a Astronaut And a Boat who m...,Sci-Fi,13
5240,ZELLWEGER,MINNIE,RAGING AIRPLANE,A Astounding Display of a Secret Agent And a T...,Sci-Fi,13
5241,ZELLWEGER,MINNIE,HYSTERICAL GRAIL,A Amazing Saga of a Madman And a Dentist who m...,Sports,15
5242,ZELLWEGER,MINNIE,PICKUP DRIVING,A Touching Documentary of a Husband And a Boat...,Sports,16
5243,ZELLWEGER,MINNIE,GROOVE FICTION,A Unbelieveable Reflection of a Moose And a A ...,Sports,18
5244,ZELLWEGER,MINNIE,TALENTED HOMICIDE,A Lacklusture Panorama of a Dentist And a Fore...,Sports,29
5245,ZELLWEGER,MINNIE,MADIGAN DORADO,A Astounding Character Study of a A Shark And ...,Travel,10

In [13]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 5246 entries, 0 to 5245
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   last_name           5246 non-null   str
 1   first_name          5246 non-null   str
 2   title               5246 non-null   str
 3   description         5246 non-null   str
 4   genre               5246 non-null   str
 5   no_of_times_rented  5246 non-null   int64
dtypes: int64(1), str(5)
memory usage: 246.0 KB

Looking at the info results, I can determine the number of rows and columns in the DataFrame. I can also see the column names, the data types, and whether any columns have missing values. This helps me understand the structure of the data before analyzing it.

In [14]:
df2.describe()

       no_of_times_rented
count         5246.000000
mean            16.770873
std              6.626960
min              4.000000
25%             11.000000
50%             16.000000
75%             21.000000
max             34.000000

Looking at the describe results, I can see useful statistics like count, mean, minimum, maximum, and standard deviation for numeric columns. These are useful for understanding the spread of the data. Some summaries may not be as useful if the numbers are ID values, because IDs are labels and not measurements.

In [16]:
df3 = pd.read_csv("northwind_example.csv")

df3

,ProductID,ProductName,SupplierID,CategoryID,QuantityPerUnit,UnitPrice,UnitsInStock,UnitsOnOrder,ReorderLevel,Discontinued
0,1,Chai,1,1,10 boxes x 20 bags,18.00,39,0,10,0
1,2,Chang,1,1,24 - 12 oz bottles,19.00,17,40,25,0
2,3,Aniseed Syrup,1,2,12 - 550 ml bottles,10.00,13,70,25,0
3,4,Chef Anton's Cajun Seasoning,2,2,48 - 6 oz jars,22.00,53,0,0,0
4,5,Chef Anton's Gumbo Mix,2,2,36 boxes,21.35,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...
72,73,Rd Kaviar,17,8,24 - 150 g jars,15.00,101,0,5,0
73,74,Longlife Tofu,4,7,5 kg pkg.,10.00,4,20,5,0
74,75,Rhnbru Klosterbier,12,1,24 - 0.5 l bottles,7.75,125,0,25,0
75,76,Lakkalikri,23,1,500 ml,18.00,57,0,20,0
76,77,Original Frankfurter grne Soe,12,2,12 boxes,13.00,32,0,15,0

In [17]:
df3.describe()

,ProductID,SupplierID,CategoryID,UnitPrice,UnitsInStock,UnitsOnOrder,ReorderLevel,Discontinued
count,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000
mean,39.000000,13.649351,4.116883,28.866364,40.506494,10.129870,12.467532,0.103896
std,22.371857,8.220267,2.395028,33.815111,36.147222,23.141072,10.931105,0.307127
min,1.000000,1.000000,1.000000,2.500000,0.000000,0.000000,0.000000,0.000000
25%,20.000000,7.000000,2.000000,13.250000,15.000000,0.000000,0.000000,0.000000
50%,39.000000,13.000000,4.000000,19.500000,26.000000,0.000000,10.000000,0.000000
75%,58.000000,20.000000,6.000000,33.250000,61.000000,0.000000,25.000000,0.000000
max,77.000000,29.000000,8.000000,263.500000,125.000000,100.000000,30.000000,1.000000

Looking at the describe results for df3, I can see summary statistics for the numeric columns. These results may be different from df2 because this dataset may have different types of numeric values. Some columns may represent real measurements like price or quantity, while others may only represent ID numbers. The useful insights depend on what each column actually represents.

## Coding a DataFrame

In [18]:
test_data = {
    "ID": [1, 2, 3, 4, 5, 6, 7, 8],
    "Name": ["Alicia", "Bob", "Charlie", "Dominic", "Eve", "Frank", "Grace", "Heidi"],
    "Age": [25, np.nan, 22, 19, 31, 35, np.nan, 18],
    "City": ["NY", "LA", "Chicago", "Houston", "Phoenix", "Boston", "Austin", "San Diego"],
    "Score": [85, 92, -1, 65, 78, np.nan, 55, 90]
}

In [19]:
df4 = pd.DataFrame(test_data)

df4

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
2   3  Charlie  22.0    Chicago   -1.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
5   6    Frank  35.0     Boston    NaN
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

In [21]:
df4.to_csv("test_data.csv", index=False)