# Exercise 2.C Working with multiple DataFrames

In [1]:
import numpy as np
import pandas as pd

## Basic Aggregations

In [2]:
data = {
    'Product': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'],
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North'],
    'Units_Sold': [10, 15, 20, 5, 10, 15, 10, 5, 15],
    'Price': [100, 200, 150, 100, 200, 150, 100, 200, 150]
}

df_sales = pd.DataFrame(data)

df_sales

  Product Region  Units_Sold  Price
0       A  North          10    100
1       B  South          15    200
2       C   East          20    150
3       A   West           5    100
4       B  North          10    200
5       C  South          15    150
6       A   East          10    100
7       B   West           5    200
8       C  North          15    150

In [3]:
df_sales['Revenue'] = df_sales['Units_Sold'] * df_sales['Price']

df_sales

  Product Region  Units_Sold  Price  Revenue
0       A  North          10    100     1000
1       B  South          15    200     3000
2       C   East          20    150     3000
3       A   West           5    100      500
4       B  North          10    200     2000
5       C  South          15    150     2250
6       A   East          10    100     1000
7       B   West           5    200     1000
8       C  North          15    150     2250

In [5]:
total_units_sold = df_sales['Units_Sold'].sum()
total_revenue = df_sales['Revenue'].sum()

print("Total Units Sold:", total_units_sold)
print("Total Revenue:", total_revenue)

Total Units Sold: 105
Total Revenue: 16000

In [6]:
average_units_sold = df_sales['Units_Sold'].mean()
average_revenue = df_sales['Revenue'].mean()

print("Average Units Sold:", average_units_sold)
print("Average Revenue:", average_revenue)

Average Units Sold: 11.666666666666666
Average Revenue: 1777.7777777777778

## Grouping Data

In [7]:
product_totals = df_sales.groupby('Product')[['Units_Sold', 'Revenue']].sum()

product_totals

         Units_Sold  Revenue
Product
A                25     2500
B                30     6000
C                50     7500

In [8]:
region_averages = df_sales.groupby('Region')[['Units_Sold', 'Revenue']].mean()

region_averages

        Units_Sold  Revenue
Region
East     15.000000   2000.0
North    11.666667   1750.0
South    15.000000   2625.0
West      5.000000    750.0

In [9]:
product_region_totals = df_sales.groupby(['Product', 'Region'])[['Units_Sold', 'Revenue']].sum()

product_region_totals

                Units_Sold  Revenue
Product Region
A       East            10     1000
        North           10     1000
        West             5      500
B       North           10     2000
        South           15     3000
        West             5     1000
C       East            20     3000
        North           15     2250
        South           15     2250

## Sorting and Ranking Data

In [10]:
df_sales.sort_values('Units_Sold', ascending=True)

  Product Region  Units_Sold  Price  Revenue
3       A   West           5    100      500
7       B   West           5    200     1000
4       B  North          10    200     2000
0       A  North          10    100     1000
6       A   East          10    100     1000
1       B  South          15    200     3000
5       C  South          15    150     2250
8       C  North          15    150     2250
2       C   East          20    150     3000

In [11]:
df_sales.sort_values('Revenue', ascending=False)

  Product Region  Units_Sold  Price  Revenue
1       B  South          15    200     3000
2       C   East          20    150     3000
8       C  North          15    150     2250
5       C  South          15    150     2250
4       B  North          10    200     2000
0       A  North          10    100     1000
6       A   East          10    100     1000
7       B   West           5    200     1000
3       A   West           5    100      500

In [12]:
df_sales['Revenue_Rank'] = df_sales['Revenue'].rank(ascending=False, method='dense')

df_sales

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank
0       A  North          10    100     1000           4.0
1       B  South          15    200     3000           1.0
2       C   East          20    150     3000           1.0
3       A   West           5    100      500           5.0
4       B  North          10    200     2000           3.0
5       C  South          15    150     2250           2.0
6       A   East          10    100     1000           4.0
7       B   West           5    200     1000           4.0
8       C  North          15    150     2250           2.0

## Merging DataFrames

In [14]:
product_data = {
    'Product': ['A', 'B', 'C'],
    'Category': ['Electronics', 'Furniture', 'Appliances']
}

df_products = pd.DataFrame(product_data)

df_products

  Product     Category
0       A  Electronics
1       B    Furniture
2       C   Appliances

In [15]:
df_merged = pd.merge(df_sales, df_products, on='Product')

df_merged

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank     Category
0       A  North          10    100     1000           4.0  Electronics
1       B  South          15    200     3000           1.0    Furniture
2       C   East          20    150     3000           1.0   Appliances
3       A   West           5    100      500           5.0  Electronics
4       B  North          10    200     2000           3.0    Furniture
5       C  South          15    150     2250           2.0   Appliances
6       A   East          10    100     1000           4.0  Electronics
7       B   West           5    200     1000           4.0    Furniture
8       C  North          15    150     2250           2.0   Appliances

In [16]:
category_revenue = df_merged.groupby('Category')['Revenue'].sum()

category_revenue

Category
Appliances     7500
Electronics    2500
Furniture      6000
Name: Revenue, dtype: int64

## Conclusion

In this exercise, I practiced working with multiple DataFrames in pandas. I learned how to create a DataFrame, add calculated columns, use basic aggregation functions like sum and mean, group data by product and region, sort and rank values, and merge two DataFrames together. This exercise helped me understand how pandas can be used to organize, summarize, and analyze business sales data.